### PR TITLE
Require PHP 7.1+ at runtime

### PR DESCRIPTION
**Pull request by glensc**
this updates php version from 5.6 to 7.1

- 5.6: (eol: 2018-12-31) was required due pear mail and mime packages, which requirement was dropped in [3.4.0 (2018-04-22)](https://github.com/eventum/eventum/releases/tag/v3.4.0)
- 7.0: was supported until 2018-12-03
- 7.1: i've used 7.1 for development for a while and it is still supported until 2019-12-01
- 7.2 and 7.3: have some extensions missing or problematic (notably ext-imap)

see:
- https://secure.php.net/supported-versions.php
- https://secure.php.net/eol.php

If you are upgrading PHP engine, it is recommended to update to latest 3.5.x, update PHP engine to 7.1, then upgrade to Eventum 3.6.0.

----

composer dependencies updated:
```

Installing dependencies (including require-dev) from lock file
Package operations: 4 installs, 23 updates, 3 removals
  - Removing symfony/polyfill-php70 (v1.10.0)
  - Removing symfony/debug (v3.4.20)
  - Removing container-interop/container-interop (1.2.0)
  - Updating doctrine/inflector (v1.1.0 => v1.3.0): Loading from cache
  - Installing symfony/contracts (v1.0.2): Loading from cache
  - Updating symfony/console (v3.4.20 => v4.2.1): Loading from cache
  - Updating doctrine/instantiator (1.0.5 => 1.1.0): Loading from cache
  - Installing doctrine/event-manager (v1.0.0): Loading from cache
  - Updating doctrine/cache (v1.6.2 => v1.8.0): Loading from cache
  - Updating doctrine/dbal (v2.5.13 => v2.9.1): Loading from cache
  - Updating doctrine/annotations (v1.4.0 => v1.6.0): Loading from cache
  - Installing doctrine/reflection (v1.0.0): Loading from cache
  - Updating doctrine/collections (v1.4.0 => v1.5.0): Loading from cache
  - Installing doctrine/persistence (v1.1.0): Loading from cache
  - Updating doctrine/common (v2.7.3 => v2.10.0): Loading from cache
  - Updating doctrine/orm (v2.5.14 => v2.6.3): Loading from cache
  - Updating php-di/invoker (1.3.3 => 2.0.0): Loading from cache
  - Updating mnapoli/silly (1.5.1 => 1.7.0): Loading from cache
  - Updating paragonie/random_compat (v2.0.17 => v9.99.99): Loading from cache
  - Updating symfony/event-dispatcher (v3.4.20 => v4.2.1): Loading from cache
  - Updating symfony/filesystem (v3.4.20 => v4.2.1): Loading from cache
  - Updating symfony/http-foundation (v3.4.20 => v4.2.1): Loading from cache
  - Updating symfony/options-resolver (v3.4.20 => v4.2.1): Loading from cache
  - Updating symfony/ldap (v3.4.20 => v4.2.1): Loading from cache
  - Updating symfony/security-core (v3.4.20 => v4.2.1): Loading from cache
  - Updating symfony/security-csrf (v3.4.20 => v4.2.1): Loading from cache
  - Updating symfony/yaml (v3.4.20 => v4.2.1): Loading from cache
  - Updating symfony/serializer (v3.4.20 => v4.2.1): Loading from cache
  - Updating symfony/config (v3.4.20 => v4.2.1): Loading from cache
  - Updating theorchard/monolog-cascade (0.5.0 => dev-master 9b46361):  Checking out 9b46361a73
symfony/contracts suggests installing psr/cache (When using the Cache contracts)
symfony/contracts suggests installing symfony/cache-contracts-implementation
```

### CODE REVIEW

**Comment by glensc** [comment]
composer deps updated fine.

@balsdorf what else to check? and you already run on 7.x right?

**Comment by balsdorf** [comment]
Looks good. Yes we are running 7.1, need to test an upgrade to 7.3 when extensions are available

**Comment by glensc** [comment]
ok, need to update zend-mail 2.4 to official release, as phplint fails when making release with 7.1 version:

https://travis-ci.org/glensc/eventum/jobs/470098092

```
./vendor/zendframework/zend-mail/src/Transport/Null.php=Fatal error: Cannot use 'Null' as class name as it is reserved in ./vendor/zendframework/zend-mail/src/Transport/Null.php on line 22
```

and `symfony/polyfill-php70` syntax lint needs to be dropped, or `composer.json` updated not to install that package

**Comment by glensc** [comment]
the symfony polyfill will go away once symfony upgraded to 4.0:
- https://github.com/symfony/flex/issues/14#issuecomment-291714199

**Comment by glensc** [comment]
updated symfony to 4.x (4.2.1)

however monolog cascade is installed via `dev-master` now:


```
Installing dependencies (including require-dev) from lock file
Package operations: 1 install, 12 updates, 2 removals
  - Removing symfony/polyfill-php70 (v1.10.0)
  - Removing symfony/debug (v3.4.20)
  - Installing symfony/contracts (v1.0.2): Loading from cache
  - Updating symfony/console (v3.4.20 => v4.2.1): Loading from cache
  - Updating symfony/event-dispatcher (v3.4.20 => v4.2.1): Loading from cache
  - Updating symfony/filesystem (v3.4.20 => v4.2.1): Loading from cache
  - Updating symfony/http-foundation (v3.4.20 => v4.2.1): Loading from cache
  - Updating symfony/options-resolver (v3.4.20 => v4.2.1): Loading from cache
  - Updating symfony/ldap (v3.4.20 => v4.2.1): Loading from cache
  - Updating symfony/security-core (v3.4.20 => v4.2.1): Loading from cache
  - Updating symfony/security-csrf (v3.4.20 => v4.2.1): Loading from cache
  - Updating symfony/yaml (v3.4.20 => v4.2.1): Loading from cache
  - Updating symfony/serializer (v3.4.20 => v4.2.1): Loading from cache
  - Updating symfony/config (v3.4.20 => v4.2.1): Loading from cache
  - Updating theorchard/monolog-cascade (0.5.0 => dev-master 9b46361):  Checking out 9b46361a73
symfony/contracts suggests installing psr/cache (When using the Cache contracts)
symfony/contracts suggests installing symfony/cache-contracts-implementation ()
symfony/contracts suggests installing symfony/service-contracts-implementation ()
symfony/contracts suggests installing symfony/translation-contracts-implementation ()
Generating autoload files
```

reported and asked for new release: https://github.com/theorchard/monolog-cascade/pull/88

**Comment by glensc** [comment]
@balsdorf not sure how to handle the upgrade here. if i make 3.6.0 only workable with 7.x, then how one should upgrade? as the upgrade procedure runs (at least for me) in same process: install new version, run post upgrade scripts. and there should be some grace period for engine update to allow troubleshooting (easier to downgrade php engine than rollback db migrations).

the 3.5.x probably runs fine with 7.1, so tell people to use 7.1 before upgrade and best to upgrade to latest 3.5 first?

or still allow 5.6 packages (need to downgrade some dependencies) and force bump sometime later php engine requirement?

**Comment by glensc** [comment]
@balsdorf i think that's the way to got: https://github.com/eventum/eventum/pull/426#issuecomment-451295475

tell people to update to 7.1 then update to 3.6.0, and say that 3.5.x is 7.1 compatible.

**Comment by glensc** [comment]
@balsdorf added such notice for changelog:

```
Upgrading to 3.6.x versions requires that you upgrade to 3.2.0 version first.
Eventum 3.6.x requires PHP 7.1, see [#426].
If you are upgrading PHP engine, it is recommended to update to latest 3.5.x,
update PHP engine to 7.1, then upgrade to Eventum 3.6.x.
```

**Comment by balsdorf** [comment]
Sorry for not responding earlier.

That sounds good to me. These multi-version upgrades can be awful but I don't see any other way around it.

**Comment by glensc** [comment]
# process_mail_queue - Zend\ServiceManager type error

@balsdorf you don't have anything like this?

```
➔ ./bin/process_mail_queue.php
app.ERROR: Uncaught Exception TypeError: "Argument 1 passed to Zend\ServiceManager\AbstractPluginManager::__construct() must be an instance of Zend\ServiceManager\ConfigInterface or null, instance of Zend\ServiceManager\ServiceManager given, called in /Users/glen/scm/eventum/eventum/vendor/zendframework/zend-mail/src/Transport/Smtp.php on line 133" at /Users/glen/scm/eventum/eventum/vendor/zendframework/zend-servicemanager/src/AbstractPluginManager.php line 62 {"exception":"[object] (TypeError(code: 0): Argument 1 passed to Zend\\ServiceManager\\AbstractPluginManager::__construct() must be an instance of Zend\\ServiceManager\\ConfigInterface or null, instance of Zend\\ServiceManager\\ServiceManager given, called in /Users/glen/scm/eventum/eventum/vendor/zendframework/zend-mail/src/Transport/Smtp.php on line 133 at /Users/glen/scm/eventum/eventum/vendor/zendframework/zend-servicemanager/src/AbstractPluginManager.php:62)"} {"file":null,"line":null,"class":null,"function":null,"memory_usage":"6 MB","memory_peak_usage":"6 MB","version":"3.6.0-dev-gd819dbc","usr_id":""}

➔ php --version
PHP 7.1.25 (cli) (built: Dec  7 2018 08:20:45) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.1.0, Copyright (c) 1998-2018 Zend Technologies
    with Zend OPcache v7.1.25, Copyright (c) 1999-2018, by Zend Technologies
    with Xdebug v2.6.0, Copyright (c) 2002-2018, by Derick Rethans
```

**Comment by balsdorf** [comment]
Nope, no errors for me on PHP 7.1.17. I am not running the latest Eventum
in production yet though.

**Pull request merged**
