### PR TITLE
Added setup option to disable timeago

### PR DESCRIPTION
**Pull request by balsdorf**
Our internal users do not like time ago so I added a setup option to disable it. It is enabled by default.

### CODE REVIEW

**Comment by glensc** [comment]
it should came from user prefs instead, like noted in original PR implementing the feature: #116

having it configured in two places makes it confusing, altho i like the default coming from setup, i.e could be useful for new users, so maybe leave your change in, but add per user preference as well?

and timeago should be always there, just default should be human readable vs raw, so having it off you could still obtain timeago by clicking or hovering.

so what you think? as if so, could do user pref later, still keep this PR as is

**Comment by glensc** [comment]
actually, i went ahead and just implemented the disabled state behaviour, so just user preference option missing

**Comment by balsdorf** [comment]
Thanks for implementing the disabled state. I went ahead and made it a user preference.

I also decided to remove "timeago" from the actual setup file name, changed it to "relative_date" so we aren't tied to one specific library name in the future

**Comment by glensc** [comment]
there's seem to be mix of `enabled`, `1` and `0` values. should stay consistent, use everywhere `enabled` or the numbers, i would prefer numbers, as we may have in the  future value `2` for some specific behavior.

and as i look the code, imho it's broken as to dom you write `enabled`, but in `main.js` you check for `1`

**Comment by balsdorf** [comment]
setup uses "enabled" while user preferences uses 1 and 0. I don't like it either but wanted to stay consistent with each section. Changing setup to use 1 and 0 was beyond the scope of this PR.

I write the value of upr_relative_date to the DOM which will be 1 or 0. For existing users I check if "enabled" == 1 but for new users I was just using the string so that was broken. Fixed.

**Comment by glensc** [comment]
you still need to cast it to `int`. while boolean `true` converted to string is `1`, then boolean `false` converted to string is empty string.

**Pull request merged**
