### PR TITLE
Feature: show all projects checkbox in issues list

### PR DESCRIPTION
**Pull request by martin-dufka**
I every was disgruntled cause it was too complicated to looking for all issues states in lot of projects . So I modified my issues list. I added checkbox to view all projects issue next to "hide closed" one, when user_role >= developer. 

Would be interest to merge this feature?

Thanx for discuss and proposals for modification

### CODE REVIEW

**Comment by martin-dufka** [comment]
showAllProjectsCbx

**Comment by glensc** [comment]
@martin-dufka did you close this PR on accident?

**Comment by martin-dufka** [comment]
@glensc No, it would be functional. I read your old comment about "rebase" and "amend" :) And there are too much merges and commits, so I dowloaded git finally to local and I'm testing now. :)  I'm looking for how to join it to one commit only, if it's possible. :) This pull request I created directly by github "edit files".

**Comment by glensc** [comment]
I can merge with squash option.

But here's command that should work:

```
git checkout martin-dufka-show-all-projects-in-list
git fetch origin # this should be https://github.com/eventum/eventum
git rebase origin/master
git push -f
```

and if you want to squash the commits, you can do:

```
git rebase -i origin/master
```

and pick appropriate action in editor

followed by
```
git push -f
```

**Comment by glensc** [comment]
@martin-dufka do you have "allow edits from maintainers" enabled for this PR?

i wonder how that feature works, to which remote I should push if that's enabled...

**Comment by martin-dufka** [comment]
Yes, it's  "allowed"

**Comment by glensc** [comment]
alright, rebased

some docs about maintainer pushes:
- https://help.github.com/en/articles/allowing-changes-to-a-pull-request-branch-created-from-a-fork
- https://help.github.com/en/articles/committing-changes-to-a-pull-request-branch-created-from-a-fork

**Comment by glensc** [comment]
merged, but seems I failed to create squash commit from github ui 😢

**Pull request merged**
