### PR TITLE
Fix assignment field and quick search dropdowns

### PR DESCRIPTION
**Pull request by glensc**
Revert fab53a1 and apply better.

The selector was too loose and applied unwanted selectors:
- https://github.com/eventum/eventum/pull/794#issuecomment-677665278

Fixes https://github.com/eventum/eventum/issues/916, https://github.com/eventum/eventum/issues/942

### CODE REVIEW

**Comment by glensc** [comment]
You can try a [snapshot] build of this:
- [eventum-3.9.5-41-gd2d5e0c94.tar.xz](https://github.com/eventum/eventum/releases/download/snapshot/eventum-3.9.5-41-gd2d5e0c94.tar.xz)


[snapshot]: https://github.com/eventum/eventum/releases/tag/snapshot

**Comment by vladsf** [comment]
Tested the snapshop. No effect for #942

**Comment by vladsf** [comment]
Also top "quick search form" and "bulk update tool" at the bottom are not consistent. Category/Priority/Status use different elements - top form uses Choosen, the bottom form uses plain dropdown select.

**Comment by glensc** [comment]
please test with the latest version. and make a new issue if the problem persists (this PR is merged, and discussion should be locked). preferably make a pull request with a fix. and the fix should made be consistent, all of them use jquery-chosen. and do include info what version it worked before.

**Pull request merged**
