### PR TITLE
Added option to add users to authorized repliers list when sending email

### PR DESCRIPTION
**Pull request by balsdorf**

### CODE REVIEW

**Comment by glensc** [comment]
could you rebase against current(!) master this after #120 gets merged

**Comment by balsdorf** [comment]
sure.

On Fri, Dec 11, 2015 at 9:19 AM, Elan Ruusamäe <notifications@github.com>
wrote:

> could you rebase against current(!) master this after #120
> <https://github.com/eventum/eventum/pull/120> gets merged
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/eventum/eventum/pull/123#issuecomment-163961534>.
>



-- 
Bryan Alsdorf
MariaDB Corporation | http://mariadb.com

**Comment by glensc** [comment]
#120 was merged

**Comment by balsdorf** [comment]
Rebased.

**Pull request merged**
