### PR TITLE
use zf2 config for setup config

### PR DESCRIPTION
**Pull request by glensc**
besides dual usage (via object and array),
the Setup::save takes only keys you want to modify, no need for Setup::load
and if you modify the retrieved setup, the in-memory version is modified too.

using zf2 lts version (2.4)

### CODE REVIEW

**Comment by balsdorf** [comment]
Looks good!

**Comment by glensc** [comment]
damn, you were quick to merge this time! i planned to note when PR is ready for merge adding @balsdorf note.

i forgot to check version compatibility of this.

**Comment by glensc** [comment]
looks like [composer.json](https://github.com/zendframework/zend-config/blob/release-2.4.8/composer.json#L16) specifies 5.3, but not all files pass syntax lint used in release process:

```
Parse error: syntax error, unexpected T_STRING in ./vendor/zendframework/zend-stdlib/src/Guard/AllGuardsTrait.php on line 15
Errors parsing ./vendor/zendframework/zend-stdlib/src/Guard/AllGuardsTrait.php
```

**Comment by balsdorf** [comment]
Sorry about that, last PR's I took too long on so I tried to go through
quickly this time. Next time I will wait for a @balsdorf note.

On Wed, Oct 21, 2015 at 3:22 PM, Elan Ruusamäe <notifications@github.com>
wrote:

> damn, you were quick to merge this time! i planned to note when PR is
> ready for merge adding @balsdorf <https://github.com/balsdorf> note.
>
> i forgot to check version compatibility of this.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/eventum/eventum/pull/80#issuecomment-150013922>.
>



-- 
Bryan Alsdorf
MariaDB Corporation | http://mariadb.com

**Comment by glensc** [comment]
i will just remove the conflicting files, we don't use them anyway

**Comment by glensc** [comment]
also Workflow config access part is not tested.

**Pull request merged**
