### PR TITLE
Reply as email

### PR DESCRIPTION
**Pull request by balsdorf**
Added the ability to reply to internal notes as emails

### CODE REVIEW

**Comment by glensc** [comment]
please no `else` keywords after `return` statements

also, please also add CHANGELOG entry, let's see how well github handles [merge=union](https://github.com/eventum/eventum/commit/0dead87443cf3ab1790dd2dfd27a2f314a628324)

**Comment by glensc** [comment]
would you mind swapping the columns, so that buttons are ordered as:

`reply as email` `reply as note`

i keep hitting `reply as email` button as it's the usual place to find the button

**Comment by balsdorf** [comment]
Are you talking about the small icons on the view issue page where you have the list of notes or the actual buttons on the view note popup?

**Comment by glensc** [comment]
yes

**Pull request merged**
