### PR TITLE
rewrite locking code to use flock

### PR DESCRIPTION
**Pull request by glensc**
i've planning to do this long time ago. the locking can be made really accurate in scope of one machine by using [flock](http://php.net/flock).

this should also solve user errors, who are unable to remove locks: #202

this removes writing pid files and `--fix-lock` arguments as it is no longer necessary.

the current code uses [malkusch/lock](https://github.com/malkusch/lock):
```php
$mutex->synchronized(function () use ($bankAccount, $amount) {
    $balance = $bankAccount->getBalance();
    $balance -= $amount;
    if ($balance < 0) {
        throw new \DomainException("You have no credit.");

    }
    $bankAccount->setBalance($balance);
});
```
the lock is automatically released when the code block exits.

the downside is that the locks are waited forever until the locked process still runs (lock is removed if process is terminated), this may queue up processes if one process stays running for too long.

i bet the error rate of users having stale pid files is way greater than actual situation when one process runs for very long.

however, maybe if lock is finally acquired and it had waited it over 300 seconds, assume lock acquire was unsuccessful and abort?

### CODE REVIEW

**Comment by glensc** [comment]
few things came up while developing this:

- [ProcessMailCommand](https://github.com/eventum/eventum/blob/v3.1.3/src/Command/ProcessMailCommand.php) ([process_all_emails.php](https://github.com/eventum/eventum/blob/v3.1.3/bin/process_all_emails.php)) does not have any locking code
- [Monitor::checkIRCBot()](https://github.com/eventum/eventum/blob/v3.1.3/lib/eventum/class.monitor.php#L211-L226) checks for irc bot pid

the new locking code does not write any pids, so the irc bot check will not work.

**Comment by balsdorf** [comment]
> the downside is that the locks are waited forever until the locked process still runs (lock is removed if process is terminated), this may queue up processes if one process stays running for too long.

> i bet the error rate of users having stale pid files is way greater than actual situation when one process runs for very long.

> however, maybe if lock is finally acquired and it had waited it over 300 seconds, assume lock acquire was unsuccessful and abort?

I agree with your thinking, this should be a good solution.

**Comment by glensc** [comment]
i file RFE to the library: https://github.com/malkusch/lock/issues/6

i guess can merge as is for now

**Comment by glensc** [comment]
i already merged this, but those issues did not get addressed:

https://github.com/eventum/eventum/pull/209#issuecomment-252494774

@balsdorf your comments?

**Comment by glensc** [comment]
@balsdorf ping!

**Comment by balsdorf** [comment]
Sorry missed the previous ping.

> - [ProcessMailCommand](https://github.com/eventum/eventum/blob/v3.1.3/src/Command/ProcessMailCommand.php) ([process_all_emails.php](https://github.com/eventum/eventum/blob/v3.1.3/bin/process_all_emails.php)) does not have any locking code

I don't think it needs it as multiple instances of it can run without a problem.

> - [Monitor::checkIRCBot()](https://github.com/eventum/eventum/blob/v3.1.3/lib/eventum/class.monitor.php#L211-L226) checks for irc bot pid

Not sure about this. I personally don't use the monitor class so I'd be okay with dropping it all (or at least this method for the time being). The other option be to write the pid to var/irc_bot.pid or something like that.

**Comment by glensc** [comment]
perhaps i just drop the irc bot pid checking. i use irc bot and that pid check is not valuable. it has even been wrong and creating bogus alerts in the past.

**Pull request merged**
