### PR TITLE
drop Mail_rfc822 PEAR Mail requirement

### PR DESCRIPTION
**Pull request by glensc**
the changes are done, but they need good testing, as i had to assume what some methods return. i.e RAW or QP-encoded. and the results are different, but still valid. however if eventum combines result by it's own then the statement is no longer true.

### CODE REVIEW

**Comment by glensc** [comment]
merging, as the changes seem to be in presentation layer, and been using changes from this branch it for a while for cron jobs.

**Comment by balsdorf** [comment]
This is odd, after you merged this in when I ran composer update it removed pear-core-minimal which messes up several things (trying to send mail is where I got the error).

```
Updating dependencies (including require-dev)
  - Removing pear/mail (1.3.0)
  - Removing pear/pear-core-minimal (v1.9.5)
  - Removing pear/console_getopt (v1.4.1)
```

This is odd because the other [packages](https://packagist.org/packages/pear/mail_mime) list it as a requirement still. Are you seeing this issue or is it just me?

**Comment by glensc** [comment]
i do not want to guess, please show the error trace.

**Comment by balsdorf** [comment]
When sending an email (/send.php?cat=reply&ema_id=2&issue_id=63)

Warning: require_once(PEAR.php): failed to open stream: No such file or directory in /media/bryan/bda-data/work/eventum/master/vendor/pear-pear.php.net/Mail_Mime/Mail/mime.php on line 62

Fatal error: require_once(): Failed opening required 'PEAR.php' (include_path='/media/bryan/bda-data/work/eventum/master/vendor/pear-pear.php.net/Mail_Mime:/media/bryan/bda-data/work/eventum/master/vendor/pear-pear.php.net/Mail_mimeDecode:/media/bryan/bda-data/work/eventum/master/vendor/pear-pear.php.net/Math_Stats:/media/bryan/bda-data/work/eventum/master/vendor/pear-pear.php.net/Net_Socket:/media/bryan/bda-data/work/eventum/master/vendor/pear-pear.php.net/Net_POP3:/media/bryan/bda-data/work/eventum/master/vendor/pear-pear.php.net/Net_URL:/media/bryan/bda-data/work/eventum/master/vendor/pear/pear_exception:/media/bryan/bda-data/work/eventum/master/vendor/pear-pear.php.net/Net_LDAP2:/media/bryan/bda-data/work/eventum/master/vendor/pear-pear.php.net/Text_Diff:/media/bryan/bda-data/work/eventum/master/vendor/pear/auth_sasl:/media/bryan/bda-data/work/eventum/master/vendor/pear/net_smartirc/Net:/media/bryan/bda-data/work/eventum/master/vendor/pear/net_smtp:.:/usr/share/php') in /media/bryan/bda-data/work/eventum/master/vendor/pear-pear.php.net/Mail_Mime/Mail/mime.php on line 62


I have no locally modified files. Everything is stock.

**Comment by glensc** [comment]
yeah, it's broken indeed. worked for me because i have `PEAR.php` in php include path.

there are several issues here.

1. https://pear.php.net/package/Mail_Mime mentions the dep is there:
Dependencies for Mail_Mime: PHP 5.0.0, PEAR Installer 1.6.0

2. the downloaded mail_mime from pear
https://pear.php.net/package/Mail_Mime/download/
http://download.pear.php.net/package/Mail_Mime-1.10.0.tgz
seems xml does not contain pear dependencies in "normal" place:
```xml
 <dependencies>
  <required>
   <php>
    <min>5.0.0</min>
   </php>
   <pearinstaller>
    <min>1.6.0</min>
   </pearinstaller>
  </required>
 </dependencies>
```
but in `<pearinstaller>` section.

2. so the composer repo generated from pear packages does not list such:
https://github.com/eventum/composer/blob/gh-pages/all.json#L2816-L2818

3. pear requirement is present in packagist version:
https://github.com/pear/Mail_Mime/blob/1.10.0/composer.json#L32

4. our composer.json specifies to use `"pear/mail_mime": "*",`
https://github.com/eventum/eventum/blob/834cd012fb447e04bc36f3401616a41e3c184590/composer.json#L76

5. however composer installs  the pear version (via our composer repo)
```
➔ composer show |grep -i mime
pear-pear.php.net/Mail_Mime       1.10.0                    Mail_Mime provides classes to deal with the creation and man...
```

**Comment by glensc** [comment]
reported to composer and to pear package:
- https://github.com/composer/composer/issues/6413
- https://pear.php.net/bugs/bug.php?id=21210

**Comment by glensc** [comment]
@balsdorf 90e12e1d solves your issue?

**Comment by balsdorf** [comment]
Yes, problem solved. Thanks!

**Pull request merged**
