### PR TITLE
rpc: setIssueStatus: validate parameters server side

### PR DESCRIPTION
**Pull request by glensc**
this is how it should had always been done.

needed by https://github.com/eventum/cli/pull/3

i replaced whatever access checks (`checkIssuePermissions`, `checkIssueAssignment`) there was with `Issue::canUpdate`. this should be sufficient right @balsdorf ?

### CODE REVIEW

**Comment by glensc** [comment]
> Finally, I'd move the logic from Issue::setRemoteStatus into the RemoteAPI class and remove that method.

yes. i thought that, but as another method uses that call, planned such change for the future

**Comment by glensc** [comment]
ok, i'll add `Access::canChangeStatus` check as well, and if remote calls is not enabled it should throw error anyway?

also i've deprecated `Issue::canUpdate` to use `Access::canUpdateIssue` directly. kept it around because maybe some workflow method uses it.

**Comment by glensc** [comment]
do you want to include check `RemoteApi::mayChangeIssue` (used by `Command_Line::checkIssueAssignment()`) into the `setIssueStatus`? or it should be rather added to `Access::canChangeStatus`?

**Comment by balsdorf** [comment]
`RemoteApi::mayChangeIssue` is poorly named right now since it just checks if the issue is assigned to the current user. It should be renamed and added to `setIssueStatus` though doing so will complicate things.

If you can find a good way to add the check and confirmation prompt to `setIssueStatus` I would, otherwise I'd leave the separate call to `Command_Line::checkIssueAssignment()` in. It unfortunately adds an extra round trip but it might be preferable to cluttering up each individual method.

**Comment by glensc** [comment]
@balsdorf ported the functions from Command_Line class. this is what you had in mind?

it involves duplication, and likely the methods could be improved to fetch data directly, but i do not wish to do those optimizations right now.

**Comment by glensc** [comment]
oh, i did not remembered i modified old cli app. but nevertheless the changes are moved to server side. the prompting for invalid input may be broken, is it worth of it to fix?

**Comment by balsdorf** [comment]
The cleanup of the code is good, but the assignment check has lost functionality. Now you cannot continue past the warning.
```
# on master
bryan@odin:cli$ ./eventum.php 1 ss discovery
WARNING: You are not currently assigned to issue #1.
These are the current details for issue #1:
         Summary: sssssssss
          Status: requirements
      Assignment: Admiñ User
  Auth. Repliers: Bryan D Alsdorf
Are you sure you want to change this issue? [default: y] -> y
OK - Status successfully changed to 'discovery' on issue #1
bryan@odin:cli$ git checkout glensc-rpc-set-status-command 
Switched to branch 'glensc-rpc-set-status-command'
bryan@odin:cli$ ./eventum.php 1 ss requirements
ERROR: You are not currently assigned to issue #1.
```
Now on the current master there actually is a bug that prevented this confirmation from showing up, looks like ever since we switched to autoloading classes. [This variable](https://github.com/eventum/eventum/blob/e9911aa619daccd0dd3ed6ef958e88ad0a2df9d1/lib/eventum/class.command_line.php#L16) doesn't end up on in the global scope so [this](https://github.com/eventum/eventum/blob/e9911aa619daccd0dd3ed6ef958e88ad0a2df9d1/lib/eventum/class.command_line.php#L323) check fails.

**Comment by glensc** [comment]
as i understand that reverting changes in command_line class restores behavior you are interested in?

**Comment by balsdorf** [comment]
Yes, with the caveat from above that autoloading broke it due to scope issues.

**Comment by glensc** [comment]
@balsdorf reverted

**Pull request merged**
