### PR TITLE
Add custom-fields functionnality to eventum_cli, to display custom field...

### PR DESCRIPTION
**Pull request by joffrey92**
Add custom-fields functionnality to eventum_cli, to display custom fields.

Usage: php eventum.phar issue-id custom-fields

### CODE REVIEW

**Comment by balsdorf** [comment]
Hi Joffrey,

Thanks for the patch. I'd like a few changes before we merge it:

Instead of adding custom fields to Issue::getDetails() where it will cause a multitude of queries on every Eventum page load, add it to lib/eventum/rpc/RemoteAPI.php:getIssueDetails().

Use custom_fields instead of customfields to match our general style.

I don't like duplicating the printIssueDetails() code into printIssueCustomFields method.

I would do these two things: 
1. Add --full option to issue details
2. Change printIssueCustomFields to only print the custom fields.

Then you can use eventum XXX --full to print full issue details or eventum XXX cf to just print custom fields.

**Comment by joffrey92** [comment]
Hi Bryan,

thanks for your great comments and recommendations.

- customfields has been renamed to custom_fields
- custom_fields fetch was moved from Issue::getDetails() to RemoteAPI::getIssueDetails() 
- custom_fields only display custom fields (I removed the check/display of quarantine as well)
- eventum.php issue-id --full calls printIssueDetails, then printIssueCustomFields
- For information:
    * Removed the \n before displaying custom fields.
    * printIssueCustomFields pads text up to 15 chars (like printIssueDetails)

Joffrey

**Comment by glensc** [comment]
@joffrey92 looks like you created this PR from your master branch. you should always create PRs from branch created from master, not directly on master.

you should reset your master branch to eventum's master before making more PR's:

```
git checkout master
git fetch origin
git reset --hard origin/master
```
otherwise your master branch has different history than eventum's master.

**Comment by glensc** [comment]
this is in fact described in [CONTRIBUTING.md](https://github.com/eventum/eventum/blob/master/CONTRIBUTING.md#pull-requests) file

**Comment by balsdorf** [comment]
I didn't point this out to Joffrey before hand, I'll make sure he does it
next time.

On Fri, Mar 20, 2015 at 1:03 PM, Elan Ruusamäe <notifications@github.com>
wrote:

> this is in fact described in CONTRIBUTING.md
> <https://github.com/eventum/eventum/blob/master/CONTRIBUTING.md#pull-requests>
> file
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/eventum/eventum/pull/39#issuecomment-84089887>.
>



-- 
Bryan Alsdorf
MariaDB Corporation | http://mariadb.com

**Comment by glensc** [comment]
we shouldn't block PR because he did not create separate branch :), but next PR which is forked from his 'master' branch history line, can be told to rebase with current master :)

**Pull request merged**
