### PR TITLE
Fix `sort_by` not being filtered in search form

### PR DESCRIPTION
**Pull request by noobpk**
Check sort_by value before query

Check the sort_by value in the request with the default table before entering the query.
Fix bug Time-Based Blind SQL Injection

- Disclosure: https://huntr.dev/bounties/668789af-8781-461c-99bb-d159e5a1d877/

### CODE REVIEW

**Comment by noobpk** [comment]
@glensc I know how to PR fix time-base blind SQL without getting involved in XSS PR. Sorry about that :(

**Comment by glensc** [comment]
@noobpk rebase to remove foreign commits:

```
git checkout fix-timebase-sql
git fetch https://github.com/eventum/eventum
git rebase -i FETCH_HEAD
git push --force-with-lease
```

when you ruin `git rebase`, it will fire and editor, you remove lines containing commits you do not want.

official doc:
- https://git-scm.com/docs/git-rebase

there are tons of posts about "git interactive rebase", probably other tools if you not comfortable with command line

**Comment by glensc** [comment]
Edit PR body and title to remove irrelevant info (that other PR)

**Comment by glensc** [comment]
rebased, added changelog myself. enabled auto merge

ps: fixed "Disclosure" typo in your commit message.

**Comment by glensc** [comment]
Damn, the PR is buggy. should have tested it locally.

```
Notice: Undefined variable: default_sort_by_options in eventum-3.10.7-18-g9b1e14f15/lib/eventum/class.search.php on line 377

Warning: in_array() expects parameter 2 to be array, null given in eventum-3.10.7-18-g9b1e14f15/lib/eventum/class.search.php on line 377
```

**Comment by glensc** [comment]
However, the `$sort_by` was previously escaped by `DB_Helper::escapeString()`:
- https://github.com/eventum/eventum/blob/v3.10.7/lib/eventum/class.search.php#L367-L372

are you saying the method is not escaping properly?

**Comment by glensc** [comment]
Also, this fix completely disables searching by custom fields:
- https://github.com/eventum/eventum/blob/v3.10.7/lib/eventum/class.search.php#L369

**Comment by glensc** [comment]
And resetting the `$sort_by = ''` will totally crash the application with 500 error because then the SQL is built with order column but not value:

```sql
ORDER BY desc, iss_id DESC
```

- https://github.com/eventum/eventum/blob/v3.10.7/lib/eventum/class.search.php#L378

**Comment by glensc** [comment]
@noobpk where or how did you obtain what to fill as `$sort_by` whitelisted values?

**Comment by glensc** [comment]
ok. there's dropdown for sort_by, let's go with that:

```html
<label>Sort By<br />
  | <select name="sort_by">
  | <option value="last_action_date" >Last Action Date</option>
  | <option value="pri_rank" >Priority</option>
  | <option value="iss_id" >Issue ID</option>
  | <option value="sta_rank" >Status</option>
  | <option value="iss_summary" >Summary</option>
  | </select>
  | </label>
```

**Comment by glensc** [comment]
New fix:
- https://github.com/eventum/eventum/pull/1255

so far the injected SQL is not appearing in the query log.

**Comment by noobpk** [comment]
> Damn, the PR is buggy. should have tested it locally.
> 
> ```
> Notice: Undefined variable: default_sort_by_options in eventum-3.10.7-18-g9b1e14f15/lib/eventum/class.search.php on line 377
> 
> Warning: in_array() expects parameter 2 to be array, null given in eventum-3.10.7-18-g9b1e14f15/lib/eventum/class.search.php on line 377
> ```

ops!! sorry about that. my mistake :((

**Comment by glensc** [comment]
> ops!! sorry about that. my mistake :((

well. the whole thing was untested. see other notes as well. had to re-do the whole fix

**Pull request merged**
