### PR TITLE
Allow issue view access to be restricted to assignees or groups

### PR DESCRIPTION
**Pull request by balsdorf**
This replaces the "Private" field functionality with something that is a bit more flexible.

I believe all  feedback on my initial commit has been handled.

### CODE REVIEW

**Comment by balsdorf** [comment]
@glensc Anymore feedback on this? I believe I addressed all your items of concern from the first commit.

**Comment by glensc** [comment]
I have not yet tested this. we use Private feature sometimes, and i want to be sure that functionality is preserved.

**Comment by balsdorf** [comment]
One thing I realized is lacking is an ability to set it "restricted" when
creating an issue. I'll be adding that this week.

On Wed, Feb 17, 2016 at 1:29 AM, Elan Ruusamäe <notifications@github.com>
wrote:

> I have not yet tested this. we use Private feature sometimes, and i want
> to be sure that functionality is preserved.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/eventum/eventum/pull/141#issuecomment-185074039>.
>



-- 
Bryan Alsdorf
MariaDB Corporation | http://mariadb.com

**Comment by glensc** [comment]
> One thing I realized is lacking is an ability to set it "restricted" when
> creating an issue. I'll be adding that this week.

seems i forgot this and went ahead and merged it already. submit separate PR please

**Pull request merged**
