### PR TITLE
add doctrine as orm

### PR DESCRIPTION
**Pull request by glensc**
this is first integration, replacing previously hand cooked scm and issuerelation models with doctrine ways.

- [x] interface to obtain repository classes: `$repo = Doctrine::getEntityManager()->getRepository(Entity\Project::class)`
- [x] datetime and timezone: http://docs.doctrine-project.org/projects/doctrine-orm/en/latest/cookbook/working-with-datetime.html
- [x] proxy dir in `var/`
- [x] production vs dev mode

drop (convert) previous Entity/Repository classes (not using doctrine)
- [x] src/Model/Repository/BaseRepository.php
  - [x] src/Model/Repository/CommitRepository.php
  - [x] src/Model/Repository/IssueAssociationRepository.php
- [x] src/Model/Entity/BaseModel.php
  - [x] src/Model/Entity/CommitFile.php
  - [x] src/Model/Entity/Commit.php
  - [x] src/Model/Entity/CommitRepo.php
  - [x] src/Model/Entity/GitlabScmPayload.php
  - [x] src/Model/Entity/IssueAssociation.php
  - [x] src/Model/Entity/IssueCommit.php
  - [x] src/Model/Entity/ScmPayloadInterface.php
  - [x] src/Model/Entity/StdScmPayload.php

created new entity models:
- [x] `src/Model/Entity/User.php`
- [x] `src/Model/Entity/Project.php`

created new repository classes:
- [x] `src/Model/Repository/ProjectRepository.php`
- [x] `src/Model/Repository/UserRepository.php`

### CODE REVIEW

**Comment by glensc** [comment]
use LEFT join or UNION for issueassociation query

```sql

SET @issue_id := 3;

SELECT isa_associated_id
FROM issue_association a1
WHERE isa_issue_id = @issue_id
UNION SELECT isa_issue_id
      FROM issue_association a2
      WHERE isa_associated_id = @issue_id;


SELECT DISTINCT COALESCE(a1.isa_associated_id, a2.isa_issue_id)
FROM issue_association a
  LEFT JOIN issue_association a1 ON (a.isa_associated_id = a1.isa_issue_id)
  LEFT JOIN issue_association a2 ON (a.isa_issue_id = a2.isa_associated_id)
WHERE
  a1.isa_issue_id = @issue_id OR a2.isa_associated_id = @issue_id;

```

**Comment by lauripiisang** [comment]
Without the `where`
```sql
SELECT DISTINCT COALESCE(a2.isa_issue_id, a3.isa_associated_id) AS loll
FROM issue_association a
  LEFT JOIN issue_association a2 ON a2.isa_associated_id = 3 
    AND a.isa_associated_id = a2.isa_associated_id
  LEFT JOIN issue_association a3 ON a3.isa_issue_id = 3
    AND a.isa_issue_id = a3.isa_issue_id;
```

**Comment by glensc** [comment]
@balsdorf i want to merge this sooner as base principles are in place. don't want to have long lived branch again. currently `issue_association` is implemented using doctrine only. however it needs cleanup, some non-repository related code moved out of it. possibly using [command pattern](https://en.wikipedia.org/wiki/Command_pattern).

i'll probably not even finish `commit*` tables related conversion in this PR as originally planned, as it also needs cleanup, which can be done/tested in separate PR.

however, having this merged, should start next version, right? 3.4.0 that is?

**Comment by balsdorf** [comment]
@glensc I'll try to test this week. I just went through the code and it looks fine (though I remember how ugly I think ORM code looks). 

I'll let you know how the test works

**Comment by glensc** [comment]
other projects to solve UTCDateTimeType:
- https://github.com/braincrafted/doctrine-bundle
- https://github.com/SooMedia/doctrine-utcdatetime
- https://github.com/Soullivaneuh/doctrine-dbal-utc-datetime
- https://github.com/vincentdieltiens/doctrine-utc-datetime

could switch to use to them if they are suitable

**Comment by glensc** [comment]
regarding timestamps, could use some timestampable extension: https://stackoverflow.com/a/18946869/2314626

**Comment by glensc** [comment]
should be complete from my side, but want to release last 3.3.x before merging this.

**Comment by glensc** [comment]
[3.3.4](https://github.com/eventum/eventum/releases/tag/v3.3.4) was released, merging

**Comment by glensc** [comment]
Should read [Auto-generating Proxy Classes](http://docs.doctrine-project.org/projects/doctrine-orm/en/latest/reference/advanced-configuration.html#auto-generating-proxy-classes-optional) and [Development vs Production Configuration](http://docs.doctrine-project.org/projects/doctrine-orm/en/latest/reference/advanced-configuration.html#development-vs-production-configuration) regarding Doctrine proxies and configure the application accordingly.

**Pull request merged**
