### PR TITLE
Allow separate role for editing custom fields vs viewing.

### PR DESCRIPTION
**Pull request by balsdorf**

### CODE REVIEW

**Comment by balsdorf** [comment]
I need to do some additional testing but wanted to get this out there.

**Comment by glensc** [comment]
looks simple. but let us know when you feel it's ready, or merge yourself

**Comment by glensc** [comment]
please test what happens if someone sets edit_role < view_role and perhaps also show error in ui when someone does?

**Comment by balsdorf** [comment]
It actually did not cause any problems but I've added validation.

I will do some additional testing and merge tomorrow most likely.

**Pull request merged**
