### PR TITLE
typo removed "the"

### PR DESCRIPTION
**Pull request by leela52452**

### CODE REVIEW

**Comment by glensc** [comment]
haha, nice one :D

**Comment by glensc** [comment]
btw, never submit PR's from your `master` branch, as any change to your `master` branch will also appear into the Pull Request, and that is typically not the thing you want.

**Comment by glensc** [comment]
also, how did you find the typo? did you use some tool for this?

**Comment by leela52452** [comment]
> also, how did you find the typo? did you use some tool for this?

my [source](https://hosted.weblate.org/projects/eventum/translations/source/review/?type=sourcecomments)

**Comment by glensc** [comment]
ah, from weblate. unfortunately the setup is not finalized, so this will not sync back there automatically.

**Pull request merged**
