### PR TITLE
Logger config

### PR DESCRIPTION
**Pull request by glensc**
Adds support for configuring loggers via config file using [Monolog-Cascade](https://github.com/theorchard/monolog-cascade)

Main goal was to be able to add more loggers without modifying code, for example log to Slack, etc

Current approach loads:
 - config/logger.dist.php
 - config/logger.php, this file can be missing

now how to ensure people don't go and modify `config/logger.dist.php` and then get their changes lost on upgrade? or should the `config/logger.dist.php` file be moved out of config dir, to `res/` maybe?

i've chosen .php format, as it allows more flexible customization

### CODE REVIEW

**Comment by glensc** [comment]
for example i have in my local `logger.php`:

```php

if ($setup['email_error']['status'] == 'enabled') {
    // enable error mailer
    $config['handlers']['error_mailer'] = array(
        'class' => 'Eventum\\Monolog\\MailHandler',
        'level' => 'ERROR',
    );
    $config['loggers']['app']['handlers'][] = 'error_mailer';
}
```

how to share such snippets? or have these automatic?

**Comment by balsdorf** [comment]
This is great.

As far as people modifying logger.dist.php, yeah I'd move it out of config/ as people are used to changing things there.  I'd also add a huge, ugly warning to not change it.

For sharing snippets, we could have docs/examples/config/logger.php with all of them or a logger/ subdir.

**Comment by glensc** [comment]
so, `res/logger.php` ?

**Comment by balsdorf** [comment]
Yes

On Fri, Feb 19, 2016 at 2:18 AM, Elan Ruusamäe <notifications@github.com>
wrote:

> so, res/logger.php ?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/eventum/eventum/pull/146#issuecomment-186113940>.
>



-- 
Bryan Alsdorf
MariaDB Corporation | http://mariadb.com

**Comment by glensc** [comment]
moved, but i think `$setup['email_error']['status']` should be somehow automatically setup, not sure how

**Pull request merged**
