### PR TITLE
Add disable missed

### PR DESCRIPTION
**Pull request by vladsf**
LdapSyncCommand lacks an option to search and disable Eventum users missed (e.g. removed) in LDAP. Current code expects to find removed users in Inactive DN but it is not a standard approach.
This patch proposes `--disable-missed` option to check active Eventum users against LDAP. Users not found in Active DN are set inactive.

### CODE REVIEW

**Comment by glensc** [comment]
The same problem as in https://github.com/eventum/eventum/pull/1211, you need to do git interactive rebase and remove commits that are not yours and force push this branch.

see yourself the tabs:
- commits: https://github.com/eventum/eventum/pull/1220/commits
- files changed: https://github.com/eventum/eventum/pull/1220/files

**Comment by vladsf** [comment]
#1220 is compete mess. I have not changed CHANGELOG.md yet. I expected to see only 47bd550 here.

**Comment by vladsf** [comment]
I am dropping this PR.
Made repeatable `git reset HEAD^ --hard` && `git push -f` to make my fork even with upstream one.

**Comment by glensc** [comment]
so, instead of dropping PR, you should have just force pushed with cleaned history. result is the same, except you don't create duplicate PR's.

**Comment by vladsf** [comment]
GH says force-pushed may not be re-created.

**Comment by glensc** [comment]
Show the actual error output including command you tried to run.

**Comment by vladsf** [comment]
reset to the second branch (without merge issues)
```
git reset origin/disable-missed-users
git push -f
```
Unable to re-open:
Screenshot from 2021-09-30 13-28-28

**Comment by glensc** [comment]
well. now that you already created a new merge request, yeah. too late baby.

the sentence applied before you created another PR:
- https://github.com/eventum/eventum/pull/1220#issuecomment-929480949

**Pull request closed without merging**
