### PR TITLE
symmetric encryption

### PR DESCRIPTION
**Pull request by glensc**
this is something that was addressed in #102

image

- [x] class for encrypt/decrypt
- [x] use own key storage or existing private_key? -> will use new file
- [x] modify admin interface not to spit out existing passwords (if no password is provided, use existing one what is stored)
- [x] map places that store passwords
  - db: [email_account.ema_password](https://github.com/eventum/eventum/blob/v3.0.8/lib/eventum/class.email_account.php#L260)
 - config/setup.php: `database.password`
 - config/setup.php: `smtp.auth`
 - config/ldap.php: `bindpw`
- [x] figure out new db field length need ([255 is fine](https://github.com/eventum/eventum/pull/134#issuecomment-180021855))
- [x] re-code all passwords if private key is changed
- [x] make encryption optional?
- [x] figure out migration
 - for config, it's transparent (https://github.com/eventum/eventum/pull/134#issuecomment-176836486)
 - for database we run conversion once (see upgrade/patches/encrypt_passwords.php)
 - the feature will be optional
- [ ] allow enabling encryption from setup page

### CODE REVIEW

**Comment by glensc** [comment]
Config keys encryption is actually very cool:

[var_export](http://php.net/var_export) used to serialize `config/setup.php` produces `__set_state` into config file:
```php
    'password' =>                                                                                                        
    Eventum\Crypto\EncryptedValue::__set_state(array(                                                                    
       'ciphertext' => '5rphRKB88tTAWlu5VIRY+K+tneoOtm3EmuW5FuCth9qnjM9ZSJVAsZvbGpqwP5gmjlQKDLinw+x1Z70iKDXUQA',         
    )),      
```

[__set_state](https://github.com/eventum/eventum/commit/6abbf7dec350699d13db03f99df1982e250ade22) method will create new `EncryptedValue` object when deserializing

as a result, any Config key converted to `EncryptedValue` will be transparently handled in further loading/saves.

a [patch](https://github.com/eventum/eventum/commit/35f92c90185fcf87ed29899fbf5895e968e5ae8c) will set initial keys that should be encrypted and they stay that way.

**Comment by glensc** [comment]
```
mysql> select length(ema_password) from eventum_email_account;
+----------------------+
| length(ema_password) |
+----------------------+
|                  192 |
|                   86 |
+----------------------+
2 rows in set (0.00 sec)
```

255 seems enough for encrypted storage, that 86 is typical 12-byte length password encrypted, 192 is 86 byte password :)

**Comment by glensc** [comment]
**Troubleshooting** (for wiki)

In case there's problem, you can edit `config/setup.php` and replace encrypted value with plain text string. To re-crypt again, go to admin panel disable encryption and enable it again. this will re-crypt the values.

**Comment by plindry** [comment]
Nice work.

Thanks

**Pull request merged**
