### PR TITLE
setup header comment for all files

### PR DESCRIPTION
**Pull request by glensc**
configures [header_comment](https://github.com/FriendsOfPHP/PHP-CS-Fixer/blob/v1.9.1/Symfony/CS/Fixer/Contrib/HeaderCommentFixer.php) to fix all file headers.

if this is fine, will apply it to all files before merging this PR

### CODE REVIEW

**Comment by glensc** [comment]
how and where to put the former copyright holders? and how to check which year numbers are correct?

```
Copyright (c) 2003 - 2008 MySQL AB
Copyright (c) 2008 - 2010 Sun Microsystem Inc
Copyright (c) 2011 - 2015 Eventum Team
```

**Comment by glensc** [comment]
did some grepping:

```
$ git clone --depth=1 https://github.com/eventum/eventum lic && cd lic
```

```
➔ grep -hr 'Copyright (c) 2' . |sed -e 's,.*Copy,Copy,'|sort -u|grep -i mysql.ab
Copyright (c) 2003, 2004, 2005, 2006 MySQL AB                        |
Copyright (c) 2003 - 2008 MySQL AB                                   |
Copyright (c) 2008 MySQL AB                                          |
```

```
➔ grep -hr 'Copyright (c) 2' . |sed -e 's,.*Copy,Copy,'|sort -u|grep -i sun
Copyright (c) 2008 - 2010 Sun Microsystem Inc.                       |
Copyright (c) 2009 Sun Microsystem Inc.                              |
Copyright (c) 2010 Sun Microsystem Inc.                              |
```

```
➔ grep -hr 'Copyright (c) 2' . |sed -e 's,.*Copy,Copy,'|sort -u|grep -i eventum
Copyright (c) 2005-2015 Eventum Team.                                |
Copyright (c) 2008-2015 Eventum Team.                                |
Copyright (c) 2009-2015 Eventum Team.                                |
Copyright (c) 2010 - 2015 Eventum Team.                              |
Copyright (c) 2011 - 2013 Eventum Team.                              |
Copyright (c) 2011 - 2014 Eventum Team.                              |
Copyright (c) 2011-2014 Eventum Team              .                  |
Copyright (c) 2011-2015 Eventum Development Team.                    |
Copyright (c) 2011 - 2015 Eventum Team.                              |
Copyright (c) 2011-2015 Eventum Team              .                  |
Copyright (c) 2011-2015 Eventum Team         .                       |
Copyright (c) 2012 - 2015 Eventum Team.                              |
Copyright (c) 2013-2015 Eventum Team.                                |
Copyright (c) 2014 - 2015 Eventum Team.                              |
Copyright (c) 2014-2015 Eventum Team.                                |
Copyright (c) 2015 Eventum Team.                                |
Copyright (c) 2015 Eventum Team.                                     |
```

**Comment by glensc** [comment]
@balsdorf: added you as collaborator in my repo, so you can commit directly to this PR branch. i always forget to make branch from organization repo so other collaborators could update existing PR.

**Comment by balsdorf** [comment]
That header looks good to me

**Comment by glensc** [comment]
still waiting your response:

https://github.com/eventum/eventum/pull/115#issuecomment-160404119

**Comment by balsdorf** [comment]
I'd put the old copyright lines at the bottom of AUTHORS . 

I believe all these dates are the best ones to use, even though some of the dates for the "Eventum Team" in individual files list other years.

Copyright (c) 2003 - 2008 MySQL AB
Copyright (c) 2008 - 2010 Sun Microsystem Inc
Copyright (c) 2011 - 2015 Eventum Team

**Comment by glensc** [comment]
i've set `2010 - 2015` for eventum team as grep revealed it first appeared in 2010 as well.

**Comment by glensc** [comment]
merging, will do actual changes in separate commit referencing this ticket

**Comment by glensc** [comment]
hmm,

old blocks say:
```
// | This program is free software; you can redistribute it and/or modify |
// | it under the terms of the GNU General Public License as published by |
// | the Free Software Foundation; either version 2 of the License, or    |
// | (at your option) any later version.                                  |
```

meaning it's GPL-v2+ not just GPL-v2, how to proceed?

**Comment by balsdorf** [comment]
Ugh I hate this legal junk.

I think we must just change the new header message to include this
verbiage.

@copyright (c) Eventum Team
@license GNU General Public License, version 2 or later (GPL-2+)



On Mon, Nov 30, 2015 at 2:22 PM, Elan Ruusamäe <notifications@github.com>
wrote:

> hmm,
>
> old blocks say:
>
> // | This program is free software; you can redistribute it and/or modify |
> // | it under the terms of the GNU General Public License as published by |
> // | the Free Software Foundation; either version 2 of the License, or    |
> // | (at your option) any later version.                                  |
>
> meaning it's GPL-v2+ not just GPL-v2, how to proceed?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/eventum/eventum/pull/115#issuecomment-160750414>.
>



-- 
Bryan Alsdorf
MariaDB Corporation | http://mariadb.com

**Pull request merged**
