### PR TITLE
add class="chosen-select" to quick filter

### PR DESCRIPTION
**Pull request by glensc**

### CODE REVIEW

**Comment by glensc** [comment]
currently all dropdown with fixed width, so the layout breaks

image

**Comment by glensc** [comment]
@vladsf do you have someone to help out here?

**Comment by glensc** [comment]
merging as is, html/css magic still welcome when mentioned people respond.

**Comment by vladsf** [comment]
> 
> @vladsf do you have someone to help out here?

Hi @glensc, I can't help with this CSS trouble, sorry. I have seen the changes and I guess the fixed 150px width is OK solution for <table>-based layout.

**Comment by glensc** [comment]
the other table cells adjust dynamically. try it!

**Pull request merged**
