### PR TITLE
Make user notification on account creation optional

### PR DESCRIPTION
**Pull request by vladsf**
Do not send email notice if user password is not set. 
If user accounts are created outside Eventum e.g. in LDAP and then ldapsync'ed then there is no reason to send email notice with
empty password.

### CODE REVIEW

**Comment by glensc** [comment]
if my users are external none of them have passwords set in the eventum database.

**Comment by vladsf** [comment]
OK, I made notification email optional on user creation. The same way [User::update()](https://github.com/eventum/eventum/blob/76a6f6dc60100d3fa74d43f95b82a7b64a1005b0/src/Auth/Adapter/LdapAdapter.php#L279) does. 

This change does not affect current workflow and only repeats `User::update()` call.

This allows to call User::insert() with disabled notification from [LdapAuthAdapter.php](https://github.com/eventum/eventum/blob/76a6f6dc60100d3fa74d43f95b82a7b64a1005b0/src/Auth/Adapter/LdapAdapter.php) later.

**Comment by glensc** [comment]
please rebase against origin/master, rather create merge commit in merge request.

but I'll squash merge this time. consider this if you want to preserve your original commit messages after merge.

**Comment by vladsf** [comment]
Ack. Thanks!

**Pull request merged**
