### PR TITLE
Fix error with bulk update not working. 

### PR DESCRIPTION
**Pull request by balsdorf**
Proposed fix for #160

### CODE REVIEW

**Comment by glensc** [comment]
Testing tomorrow (hopefully!)

**Comment by glensc** [comment]
This pull request changed order of events are emitted:

Before:
- send issue close note
- close issue

Now:
- close issue
- send issue closed note

this broke my workflow method which re-opens issue if note is posted to closed issue, making it impossible to close issues

**Comment by balsdorf** [comment]
So this was mistakenly sending a note in addition to the "Closed Issue"
notification. Fixed now.

The issue is still closed before the note is added, but since the "closing"
flag is now passed your workflow should handle it correctly.

On Thu, Mar 31, 2016 at 4:10 AM, Elan Ruusamäe <notifications@github.com>
wrote:

> This pull request changed order of events are emitted:
>
> Before:
>
>    - send issue close note
>    - close issue
>
> Now:
>
>    - close issue
>    - send issue closed note
>
> this broke my workflow method which re-opens issue if note is posted to
> closed issue, making it impossible to close issues
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/eventum/eventum/pull/161#issuecomment-203836498>
>



-- 
Bryan Alsdorf
MariaDB Corporation | http://mariadb.com

**Comment by glensc** [comment]
well, this PR created another problem:
- I'm no longer receiving the text from "Reason for closing issue"

weird that it took so long time to notice that close issue messages do not get notified by email.

**Comment by glensc** [comment]
after this change:

```diff
[~/scm/eventum/eventum (close-notification)★] ➔ g diff
diff --git a/lib/eventum/class.note.php b/lib/eventum/class.note.php
index ff848d79c..7931959f1 100644
--- a/lib/eventum/class.note.php
+++ b/lib/eventum/class.note.php
@@ -377,7 +377,7 @@ class Note
         }

         // send notifications for the issue being updated
-        if ($options['send_notification']) {
+        if ($options['send_notification'] || true) {
             $internal_only = true;
             Notification::notify($issue_id, 'notes', $note_id, $internal_only, $options['cc']);
             Workflow::handleNewNote($prj_id, $issue_id, $usr_id, $options['closing'], $note_id);
```

I get the mails, but as [noted](https://github.com/eventum/eventum/pull/161#issuecomment-203836498) the mails are sent wrong time so they appear as opened notes


image

**Comment by glensc** [comment]
reverted in 3.7.4: https://github.com/eventum/eventum/pull/631

rather have duplicate mails than missing mail. and i'm used to that if issue is closed two mains are sent.

**Pull request merged**
