### PR TITLE
Fix bug stored xss -  Data when render on FE allows execution of arbitrary javascript code

### PR DESCRIPTION
**Pull request by noobpk**

### CODE REVIEW

**Comment by glensc** [comment]
@noobpk:

1. put PR to draft state, if it's not ready to merge
2. you can change PR state after you've created it, for example seeing you have excess commits here (look at the Commits tab)
3. rebase against `origin/master` (or whatever remote points to `https://github.com/eventum/eventum`), you have foreign commits not belonging to this PR
4. fix pr title body, they are useless right now. just take info from commit message
5. seems you have not paid attention (already reported before) you have a typo in your message: "Disclose" should be written as "Disclosure". rewrite the commit message and force push.

changing to Draft now myself as clearly this is not ready.

**Comment by glensc** [comment]
also, this bounty has not been reported to the security contact: cc5c6cdd-8030-4eb1-af75-947780ee12e0

the previous ones you had, sent a mail to my inbox so I could read them.

**Comment by glensc** [comment]
seems the origin of the problem is that your `master` is in wrong state, it has commits merged into it, not rebased. I gave you a command line on how to fix this. use it! it's also documented in project CONTRIBUTING.md

**Comment by noobpk** [comment]
> also, this bounty has not been reported to the security contact: cc5c6cdd-8030-4eb1-af75-947780ee12e0
> 
> 
> 
> the previous ones you had, sent a mail to my inbox so I could read them.

The Huntr is processing my report and will send it to you soon . ^^

**Comment by noobpk** [comment]
I will create a new PR.

**Comment by glensc** [comment]
> I will create a new PR.

Why?

Why spam maintainers with multiple PR. Now the information is spread around multiple pull requests and you didn't even point to the new pull request here or vice versa!

I gave you instructions how to fix. use them!

**Comment by noobpk** [comment]
> > I will create a new PR.
> 
> Why?
> 
> Why spam maintainers with multiple PR. Now the information is spread around multiple pull requests and you didn't even point to the new pull request here or vice versa!
> 
> I gave you instructions how to fix. use them!

Sorry about that bro. I had tried using 'fetch upstream' on my repo on github website and then I commit via 'Sourcetree'. I don't know where is wrong so I delete repo and get new fork and create new PR

**Pull request closed without merging**
