### PR TITLE
Improve attachment migration script

### PR DESCRIPTION
**Pull request by glensc**
#254 added support for attachment storage backends

- speedup migration by querying files to be migrated once (creating temporary table)
- adds [progressbar](https://symfony.com/doc/current/components/console/helpers/progressbar.html)
- truncate attachment flysystem paths to 255 bytes (original filename is stored in `issue_attachment_file`)

### CODE REVIEW

**Comment by glensc** [comment]
looks like there's problem that temp files are left around when migrating: 
https://github.com/eventum/eventum/pull/355

**Comment by glensc** [comment]
seems the phlib/flysystem-pdo#3 is worked on in https://github.com/phlib/flysystem-pdo/pull/6

```
$ composer require "phlib/flysystem-pdo:dev-ver-1.1 as 1.1.0"
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Package operations: 0 installs, 1 update, 0 removals
  - Removing phlib/flysystem-pdo (1.0.0)
  - Installing phlib/flysystem-pdo (dev-ver-1.1 0f69f24): Cloning 0f69f244fa from cache
Writing lock file
Generating autoload files
> ComponentInstaller\Installer::postAutoloadDump
Compiling component files
```

**Comment by glensc** [comment]
hmmz. how to handle this:

```
PHP Warning:  fopen(/var/lib/eventum/storage/77710/65678-OTSEBLOGI__Eesti_vädetav_allilmaliider_Assar_Paulus_ja_tema_jõk_astusid_kohtu_ette_-_DELFI_and_Gallery_Admin____Edit_gallery_and_Visible_rows_is_not_working_in_Gallery_Admin-_f fix_it_please__and_Inbox_—_Exchange__Found_382_matches_for_sear.png): failed to open stream: File name too long in /home/glen/eventum/vendor/league/flysystem/src/Adapter/Local.php on line 151
PHP Stack trace:
```

**Comment by glensc** [comment]
@balsdorf i installed eventum new database, and `issue_attachment_file_path` is nowhere to be created, but code needs it. #254 seems altering the table, assumes it's already present... hmmz?!

```
$ ./contrib/migrate_storage_adapter.php  --yes pdo local -vvv
Migrating data from 'pdo://' to 'local://'
Preparing temporary table. Please wait...

In PdoAdapter.php line 159:

  [Eventum\Db\DatabaseException (42S02)]
  SQLSTATE[42S02]: Base table or view not found: 1146 Table 'eventum.issue_attachment_file_path' doesn't exist
```

**Comment by glensc** [comment]
hmm, [20170630191008_eventum_attachments.php](https://github.com/eventum/eventum/blob/v3.3.4/db/migrations/20170630191008_eventum_attachments.php#L24) should add it. i wonder why it's missing (other tables seem to be present).

```
$ ./bin/monitor.php
ERROR: Could not find required table "issue_attachment_file_path"
$
```

**Comment by glensc** [comment]
progressbar!

```
[root@eventum2 eventum]# ./contrib/migrate_storage_adapter.php  --yes local pdo -vvv
Migrating data from 'local://' to 'pdo://'
Preparing temporary table. Please wait...
Moving 87059 file(s)
  2204/87059 [>---------------------------]   2% 51 secs/33 mins 6.2 MiB (2387: local://4284/2387-398x156.swf)
```

**Comment by glensc** [comment]
another truncation, in `issue_attachment_file_path` table because filename with 255+flysystem prefix is over 255 chars. plus there's unicode in play that in bytes it's 257 bytes.


```

  [League\Flysystem\FileNotFoundException]
  File not found at path: 81812/70152-FOTOD__Kalju_alustas_trennidega__kohal_Rivaldo_endine_tiimikaaslane__Quintieri_ja_Elhi__puudu_Lindpere__Kimbaloula_ja_Kallaste_-_Sport_and_Meeli
  ke_kiidab_tublisid_Eesti_mehi__hollandlastel_on_meie_omadelt_ikka_nii_mõdagi_õpida___-_

21:08:15 mysql{5}> select *,length(iap_flysystem_path),char_length(iap_flysystem_path) from issue_attachment_file_path where iap_iaf_id=70152\G
*************************** 1. row ***************************
                     iap_iaf_id: 70152
             iap_flysystem_path: local://81812/70152-FOTOD__Kalju_alustas_trennidega__kohal_Rivaldo_endine_tiimikaaslane__Quintieri_ja_Elhi__puudu_Lindpere__Kimbaloula_ja_Kallaste_-_Sport_and_Meelike_kiidab_tublisid_Eesti_mehi__hollandlastel_on_meie_omadelt_ikka_nii_mõdagi_õpida___-_
     length(iap_flysystem_path): 257
char_length(iap_flysystem_path): 255
1 row in set (0.00 sec)

[root@eventum2 eventum]# ls /var/lib/eventum/storage/81812|wc -c
255
```

**Comment by glensc** [comment]
so, as we have filename stored in `issue_attachment_file` as well. perhaps just make flysystem paths truncated at safe length, preserving file extension...

**Comment by glensc** [comment]
btw, flysystem move is not safe to errors. it still moved data even if there were errors (disk got full, or result filename could not be written). had to manually patch database to rollback to previous state and resume migration.

```
21:33:26 mysql{2}> update issue_attachment_file_path set iap_flysystem_path=CONCAT('legacy://', iap_iaf_id) where iap_iaf_id=70152;
Query OK, 1 row affected (0.00 sec)
Rows matched: 1  Changed: 1  Warnings: 0
```

**Comment by balsdorf** [comment]
Did it throw an error we can catch or do we need to add some explicit checks for filesystem space / verify the size on disk is the same as in DB?

**Comment by glensc** [comment]
it did throw error, but also left db inconsistent state. will try to reproduce this.

i had an idea that to first copy, if that succeeds then move, this would result at least db in consistent state

**Comment by glensc** [comment]
also, my filesystem got full in temp dir, not on intended storage path due this bug: https://github.com/eventum/eventum/pull/355#issuecomment-372618008 (which is now solved by pulling 1.1 version from a branch)

**Comment by glensc** [comment]
migrated back and forth, i think should forbid using path separators as flysystem filenames:

```
0       /var/lib/eventum/storage/16616/11848-file:/C:/DOCUME~1/MONIKA/LOCALS~1/TEMP
```

translate to backslash? `\` on unix... and um, what about windows? it has more chars it can not name a file :)

**Comment by glensc** [comment]
some more funny characters (`^C` and `^W`): 
```
[root@eventum2 storage]# l ./73658/61174-elutoa*|less
-rw-rw---- 1 root http 0 24. nov    2014 ./73658/61174-elutoa po^Crand.jpg

[root@eventum2 storage]# l ./59050/45972-*|less
-rw-rw---- 1 root http 0 21. jaan   2013 ./59050/45972-^W0-@C156><_flags.png
```

**Comment by glensc** [comment]
also some attachment filenames extracted with `'ZERO WIDTH NON-JOINER' (U+200C)` and `'ZERO WIDTH SPACE' (U+200B)`

```
filename*0*=utf-8''%54%61%67%73%20%41%64%66%6F%72%6D%2E%E2%80%8C%E2%80%8B;
filename*1*=%74%78%74

->

filename*0*=utf-8''Tags Adform.<U+200C><U+200B>;
filename*1*=txt
```

**Comment by glensc** [comment]
another funny error:

``
touch() expects parameter 1 to be a valid path, string given
``

SFO suggests it may contain `\0`: https://stackoverflow.com/a/22957831/2314626

**Comment by balsdorf** [comment]
Wow people have some crazy filenames.

The safest thing then would be to just name it with the id, though this then makes any admin work looking on the filesystem directly less obvious.

**Comment by glensc** [comment]
created separate PR (and library) for that: https://github.com/eventum/eventum/pull/356

**Pull request merged**
