### PR TITLE
scm: modularize and add gitlab adapter

### PR DESCRIPTION
**Pull request by glensc**
This PR reworks whole SCM integration. You will need 3.1.x version of scm hook scripts, requests from older versions will just do nothing.

Internally the checkins are now commit based, not file based. even CVS has commitid property. file versions are supported only for CVS, the emulation for SVN/Git was dropped.

Configuration also changed, see [/manage/scm](https://github.com/eventum/eventum/blob/master/templates/manage/scm.tpl.html#L75-L99) page for sample.

- [x] modularize scm providers
- [x] add gitlab adapter
- [x] update scm hooks to include commitid
- [x] add commit concept instead of file based revisions
- [x] update scm hooks to categorize files `added`, `modifled`, `removed`
- [x] <del>handle file renames</del>: https://github.com/eventum/eventum/pull/159#issuecomment-212006193
- [x] db migration
- [x] <del>make scm block min role = user</del>. postponed
- [x] workflow method to map commit to eventum user
- [x] use JSON for hook POST payload
- [x] <del>add date to cvs/svn hooks</del> https://github.com/eventum/scm/issues/1
- [x] test merge commits referring to issue: https://github.com/eventum/eventum/pull/159#issuecomment-212604051
- [x] <del>hooks: move configuration to commandline</del> https://github.com/eventum/scm/issues/1
- [x] <del>svn hook: add `-s`, `--stdlayout` to support finding project root</del> https://github.com/eventum/scm/issues/1

### CODE REVIEW

**Comment by glensc** [comment]
some incomplete tables. still not sure how to lay out it in database and keep CVS compatibility for file based commits. comments welcome, including the naming of table and fields.

```sql
# commit info
create table eventum_scm_commit (
    scc_id int unsigned not null auto_increment primary key,
    # 40 chars to fit git commit hashes
    scc_commit varchar(40) binary not null,
    scc_author_email varchar(255) not null,
    scc_author_name varchar(255) not null,
    scc_commit_date datetime NOT NULL DEFAULT '0000-00-00 00:00:00',
    scc_commit_url varchar(255) not null,
    scc_message mediumtext
);

# commit to issue relation
create table eventum_issue_scm_commit (
    isc_id int unsigned not null auto_increment primary key,
    isc_scc_id int unsigned not null,
    isc_iss_id int unsigned not null
);
```

**Comment by glensc** [comment]
for comparision current checkins table:

```sql
CREATE TABLE `eventum_issue_checkin` (
  `isc_id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `isc_iss_id` int(10) unsigned NOT NULL DEFAULT '0',
  `isc_reponame` varchar(255) NOT NULL DEFAULT 'default',
  `isc_module` varchar(255) NOT NULL DEFAULT '',
  `isc_filename` varchar(255) NOT NULL DEFAULT '',
  `isc_old_version` varchar(40) DEFAULT NULL,
  `isc_new_version` varchar(40) DEFAULT NULL,
  `isc_created_date` datetime NOT NULL DEFAULT '0000-00-00 00:00:00',
  `isc_username` varchar(32) NOT NULL DEFAULT '',
  `isc_commit_msg` mediumtext,
  PRIMARY KEY (`isc_id`),
  KEY `isc_iss_id` (`isc_iss_id`)
)
```

**Comment by balsdorf** [comment]
I wish we knew how many people still used CVS with Eventum or if we could just drop it. For CVS support could you add something like this?

CREATE TABLE `eventum_scm_file` (
  `scf_id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `scf_scc_id` int(10) unsigned NOT NULL DEFAULT '0',
  `scf_reponame` varchar(255) NOT NULL DEFAULT 'default',
  `scf_module` varchar(255) NOT NULL DEFAULT '',
  `scf_filename` varchar(255) NOT NULL DEFAULT '',
  `scf_old_version` varchar(40) DEFAULT NULL,
  `scf_new_version` varchar(40) DEFAULT NULL,
  PRIMARY KEY (`scf_id`),
  KEY `scf_iss_id` (`scf_iss_id`)
)

Trying to use all the common info from the main table.

**Comment by glensc** [comment]
I use CVS, I use SVN and Git as well!

**Comment by glensc** [comment]
grouped files by commit, tried to make it look good, but i'm definitely UI guru

image

**Comment by balsdorf** [comment]
I don't use this module at all but IMO that looks good.

On Thu, Mar 31, 2016 at 11:12 AM, Elan Ruusamäe <notifications@github.com>
wrote:

> grouped files by commit, tried to make it look good, but i'm definitely UI
> guru
>
> [image: image]
> <https://cloud.githubusercontent.com/assets/199095/14182552/608eb4a4-f774-11e5-9c15-0696d10d981e.png>
>
> —
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub
> <https://github.com/eventum/eventum/pull/159#issuecomment-204003926>
>



-- 
Bryan Alsdorf
MariaDB Corporation | http://mariadb.com

**Comment by glensc** [comment]
redone the block to use expendable cell layout, looks similar as notes and is more compact:

image

**Comment by glensc** [comment]
renamed files. it will show them as `added` for now:

```
➔ git show --pretty=format: --name-status 
M       gl-env
D       lll
D       setup.php
A       setup2.php
M       test
A       x

➔ git show --pretty=format: --name-status -M
M       gl-env
D       lll
R099    setup.php       setup2.php
M       test
A       x
```

**Comment by glensc** [comment]
git merges are ignored by git hook:

```
➔ git push -f origin master                                                                 
Counting objects: 3, done.
Delta compression using up to 2 threads.
Compressing objects: 100% (3/3), done.
Writing objects: 100% (3/3), 387 bytes | 0 bytes/s, done.
Total 3 (delta 2), reused 0 (delta 0)
remote: Array
remote: (
remote:     [0] => 01b121479ff4e2f141885d2e16309b9e1d5942f6
remote:     [1] => cc36b5c126e7c3e03755316be954efaf831f5b55
remote:     [2] => refs/heads/master
remote: )
remote: Array
remote: (
remote: )
To ../gitroot/
 + 01b1214...cc36b5c master -> master (forced update)

➔ git rev-list 01b121..cc36b5c1
cc36b5c126e7c3e03755316be954efaf831f5b55
➔ git rev-list --no-merges 01b121..cc36b5c1
➔  
```

**Pull request merged**
