### PR TITLE
Add an option to tune notifications on account inserts in LdapSyncCommand

### PR DESCRIPTION
**Pull request by vladsf**
Add a property to disable user notification on account insert action in LdapAdapter.php 
Justification: This adapter already [has notification turned off](https://github.com/eventum/eventum/blob/76a6f6dc60100d3fa74d43f95b82a7b64a1005b0/src/Auth/Adapter/LdapAdapter.php#L279) for user account updates. To add the same option for `User::insert()` is in accordance with the code.

It is debatable to add this option to global ldap config or not.

This PR helps to make notofications configurable in `eventum:ldap:sync` command.

### CODE REVIEW

**Comment by glensc** [comment]
how do you tune this flag? via command-line options to sync command?

also, use github draft feature rather title prefix:
- https://github.blog/2019-02-14-introducing-draft-pull-requests/

**Comment by vladsf** [comment]
Yes, I want to add `--no-notify` option to the ldap sync command.

**Comment by vladsf** [comment]
@glensc I'd like to merge it.

**Comment by glensc** [comment]
@vladsf will you rebase and fix your PR commit history, or have it squash merge again?

**Comment by vladsf** [comment]
I'd prefer to squash. Single small commit would be better in this case.

**Comment by glensc** [comment]
@vladsf ambiguity, unclear if you prefer to squash your commits yourself, or squash during merge?

**Comment by glensc** [comment]
Ok. I'm going to remove @vladsf your merge mana, as obviously you have no idea what are you doing. if you were uncertain, you would have asked, but you instead merged.

**Comment by vladsf** [comment]
OK, I guess I need some contributor guidelines. `git diff master` showed me only my changes so I pushed and click Merge.

**Comment by vladsf** [comment]
Sorry. Github allows to revert the changes.

**Comment by glensc** [comment]
Luckily, I disabled your access before you do that "revert changes", which just creates another set of commits with a merge commit.

I've reset master to 386214f12 before your merge and squashed changes from this PR to one commit ee5e6226a.

**Comment by vladsf** [comment]
Now I have `src/Console/Command/ExampleHelloCommand.php`in my pull requests. I guess I need to reset my master to the same..

**Comment by vladsf** [comment]
```
$ git reset HEAD^ --hard (x7 times)
$ git push mathnet -f
```
resolved my issues, I can submit clean PR again.

The question left - should I `git rebase upstream/master` or `git merge upstream/master` before starting a new PR?

**Comment by vladsf** [comment]
I am afraid this history rewriting might affect forked repositories.

**Comment by glensc** [comment]
`git rebase`, no merge commits to merge requests!

instead of `git reset HEAD^` 7 times, do `git reset origin/master` (or `upstream/master`) or anything that points to a commit.

**Comment by glensc** [comment]
history rewriting is done only on feature branches (pull requests). this git reset to undo your damage was one time only, unlikely anyone but you had pulled those changes.

**Pull request merged**
