### PR TITLE
show dates human friendly

### PR DESCRIPTION
**Pull request by glensc**
uses [jquery-timeago](http://timeago.yarp.com/) to print dates human readable.
to switch between human readable time ago and full timestamp, just click on the element.

could be done, but not (yet?):
- user preference to disable `timeago` formatting
- localized `timeago` messages. localized strings exist in [jquery-timeago](https://github.com/rmm5t/jquery-timeago/tree/v1.4.3/locales) project

how to check?
- code should not use `Date_Helper::getFormattedDate` method
- templates should use `{$var|format_date}` or `{$var|timeago}` modifier

----

before:
before

after:
after2

### CODE REVIEW

**Comment by glensc** [comment]
ready for merge!

**Comment by balsdorf** [comment]
So I addressed those fixmes locally and tried to push them but for some reason I can't get that to work.

I added https://github.com/glensc/eventum.git as a github remote (using the name glensc) but run into this:
git push glensc jquery-timeago
error: src refspec jquery-timeago does not match any.
error: failed to push some refs to 'https://github.com/glensc/eventum.git'

Pushing to glensc glensc/jquery-timeago said it was successful but it apparently didn't work.

**Comment by glensc** [comment]
what was your push command?

`git push https://github.com/glensc/eventum.git -u "local-branch-name"` should do

**Comment by glensc** [comment]
or i can just merge, and then you can can just apply your fixes on master branch?

**Comment by balsdorf** [comment]
Still can't get it to work so yeah, merge and I'll fix in master and figure out my git shortcomings later.

**Comment by glensc** [comment]
hey, your commits landed here. so all is well!

**Pull request merged**
